# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_First_window_base(object):
    def setupUi(self, First_window_base):
        First_window_base.setObjectName("First_window_base")
        First_window_base.resize(800, 590)
        First_window_base.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=First_window_base)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.Start_pred = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Start_pred.setGeometry(QtCore.QRect(470, 110, 251, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_pred.sizePolicy().hasHeightForWidth())
        self.Start_pred.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Start_pred.setFont(font)
        self.Start_pred.setStyleSheet("border: 2px solid #000000;\n"
"border-radius: 20px;   \n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Start_pred.setObjectName("Start_pred")
        self.Choose_dir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Choose_dir.setGeometry(QtCore.QRect(130, 110, 251, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Choose_dir.sizePolicy().hasHeightForWidth())
        self.Choose_dir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Choose_dir.setFont(font)
        self.Choose_dir.setStyleSheet("border: 2px solid #000000;\n"
"border-radius: 20px;   \n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.Choose_dir.setObjectName("Choose_dir")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 340, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        First_window_base.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=First_window_base)
        self.statusbar.setObjectName("statusbar")
        First_window_base.setStatusBar(self.statusbar)

        self.retranslateUi(First_window_base)
        QtCore.QMetaObject.connectSlotsByName(First_window_base)

    def retranslateUi(self, First_window_base):
        _translate = QtCore.QCoreApplication.translate
        First_window_base.setWindowTitle(_translate("First_window_base", "MainWindow"))
        self.label.setText(_translate("First_window_base", "Диагностика заболеваний растений"))
        self.Start_pred.setText(_translate("First_window_base", "Провести диагностику "))
        self.Choose_dir.setText(_translate("First_window_base", "Выбрать директорию"))
        self.label_2.setText(_translate("First_window_base", "                                   Имя директории"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    First_window_base = QtWidgets.QMainWindow()
    ui = Ui_First_window_base()
    ui.setupUi(First_window_base)
    First_window_base.show()
    sys.exit(app.exec())
