# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Second_window_base(object):
    def setupUi(self, Second_window_base):
        Second_window_base.setObjectName("Second_window_base")
        Second_window_base.resize(800, 590)
        Second_window_base.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=Second_window_base)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 30, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.Back_1_window = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Back_1_window.setGeometry(QtCore.QRect(560, 480, 231, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back_1_window.sizePolicy().hasHeightForWidth())
        self.Back_1_window.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Back_1_window.setFont(font)
        self.Back_1_window.setStyleSheet("border-radius: 20px;   \n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(250, 250, 250);\n"
"border: 2px solid #000000")
        self.Back_1_window.setObjectName("Back_1_window")
        self.Results = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.Results.setGeometry(QtCore.QRect(20, 80, 771, 361))
        self.Results.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.Results.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Results.setObjectName("Results")
        self.Results.setColumnCount(4)
        self.Results.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Results.setItem(0, 2, item)
        self.Results.horizontalHeader().setDefaultSectionSize(188)
        self.Excel_b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Excel_b.setGeometry(QtCore.QRect(80, 500, 221, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Excel_b.sizePolicy().hasHeightForWidth())
        self.Excel_b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Excel_b.setFont(font)
        self.Excel_b.setStyleSheet("border-radius: 20px;   \n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(250, 250, 250);\n"
"border: 2px solid #000000")
        self.Excel_b.setObjectName("Excel_b")
        self.CSV_B = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CSV_B.setGeometry(QtCore.QRect(320, 500, 221, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CSV_B.sizePolicy().hasHeightForWidth())
        self.CSV_B.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CSV_B.setFont(font)
        self.CSV_B.setStyleSheet("border-radius: 20px;   \n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(250, 250, 250);\n"
"border: 2px solid #000000")
        self.CSV_B.setObjectName("CSV_B")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 460, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        Second_window_base.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Second_window_base)
        self.statusbar.setObjectName("statusbar")
        Second_window_base.setStatusBar(self.statusbar)

        self.retranslateUi(Second_window_base)
        QtCore.QMetaObject.connectSlotsByName(Second_window_base)

    def retranslateUi(self, Second_window_base):
        _translate = QtCore.QCoreApplication.translate
        Second_window_base.setWindowTitle(_translate("Second_window_base", "MainWindow"))
        self.label.setText(_translate("Second_window_base", "Результаты диагностики"))
        self.Back_1_window.setText(_translate("Second_window_base", "Назад к выбору директории"))
        item = self.Results.horizontalHeaderItem(0)
        item.setText(_translate("Second_window_base", "Имя файла"))
        item = self.Results.horizontalHeaderItem(1)
        item.setText(_translate("Second_window_base", "Название растения"))
        item = self.Results.horizontalHeaderItem(2)
        item.setText(_translate("Second_window_base", "Результат"))
        item = self.Results.horizontalHeaderItem(3)
        item.setText(_translate("Second_window_base", "Рекомендации"))
        __sortingEnabled = self.Results.isSortingEnabled()
        self.Results.setSortingEnabled(False)
        self.Results.setSortingEnabled(__sortingEnabled)
        self.Excel_b.setText(_translate("Second_window_base", "Excel"))
        self.CSV_B.setText(_translate("Second_window_base", "CSV"))
        self.label_2.setText(_translate("Second_window_base", "Выгрузить результаты "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Second_window_base = QtWidgets.QMainWindow()
    ui = Ui_Second_window_base()
    ui.setupUi(Second_window_base)
    Second_window_base.show()
    sys.exit(app.exec())
